[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eureka"
version = "0.0.3.12"
description = "Eureka: Neuro-Symbolic ML for Scientific Discovery"
readme = "README.md"
authors = [{name = "Shubham Jangra"}]
dependencies = [
    "torch",
    "numpy",
    "scikit-learn",
    "tqdm",
    "sympy"
]
requires-python = ">=3.11"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
'Homepage' = "https://github.com/webshubham259/eureka"
'Bug Tracker' = "https://github.com/webshubham259/eureka/issues"